### ISSUE TITLE
INFOGRAFIA 

### ISSUE THREAD

**Issue by Nestor283** [SistemasTecTlaxiaco/infografia-Nestor283#2]
[Infografía Creatividad Simple Blanco.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Nestor283/files/12501801/Infografia.Creatividad.Simple.Blanco.pdf)

**Comment by Maricruz-Gomz** [comment]
Expresión de ideas 13%
Organización de la información 15%
Uso de imágenes 0%
Presentación visual  14%
Contiene ideas centrales 13%
Entregado en tiempo y forma 15%
No contiene referencias bibliográficas 0%
Calificación: 14%/20%
Evaluado por: Anais Martínez y Mari cruz Gomez

**Comment by josealfredo79** [comment]
Bien hecho y revisado
